### ISSUE TITLE
Stuttering movement

### ISSUE THREAD

**Issue by raiken-mf** [alain-bertrand/Dot-World-Maker#8]
Stuttering movement even though fps are at 60+

**Comment by bertrand-alain** [comment]
Depends on the sprites you use, it will anyhow not have more than those few frames.

**Comment by raiken-mf** [comment]
It's stuttering on the demo. Using default sprites and I've reset the game to demo state.

**Comment by bertrand-alain** [comment]
As said, the sprites have some many frames, you will not get smoother movement out of them.
