### ISSUE TITLE
Path finding

### ISSUE THREAD

**Issue by raiken-mf** [alain-bertrand/Dot-World-Maker#9]
Path finding is not quite working well when objects are in the way it doesn't move around them

**Comment by bertrand-alain** [comment]
To avoid freezing times, the path finding limits itself to a max of 5000 steps and other limitations. You may want to try to change this file https://github.com/alain-bertrand/Dot-World-Maker/blob/master/public/Engine/Logic/MovingActors/PathSolver.ts if you want to have a smarter path solver. I would consider it "good enough" for this kind of game.
